FIND_PACKAGE(PackageHandleStandardArgs)

FIND_LIBRARY(
		CUDA_DRIVER_LIBRARY
		NAMES cuda
		PATHS 
		/usr/local/lib/
		/usr/lib64/
		$ENV{CUDA_PATH}/lib/Win32)
		#$ENV{CUDA_LIB_PATH})
		#${CUDA_TOOLKIT_ROOT_DIR}/lib64)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CUDADriver DEFAULT_MSG CUDA_DRIVER_LIBRARY)