FIND_PACKAGE(PackageHandleStandardArgs)

FIND_LIBRARY(
		CUDA_DRIVER_LIBRARY
		NAMES cuda
		PATHS 
		/usr/local/lib/
		/usr/lib64/
		${CUDA_TOOLKIT_ROOT_DIR}/lib64)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(BoostNumpy DEFAULT_MSG CUDA_DRIVER_LIBRARY)