FIND_PACKAGE(PackageHandleStandardArgs)

FIND_PATH(CUDA_HELPER_MATH_DIR
		NAMES
		helper_math.h
		PATHS
		/usr/local/include
		$ENV{NVCUDASAMPLES_ROOT}/common/inc
		${CUDA_TOOLKIT_ROOT_DIR}/samples/common/inc)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(CUDAMath DEFAULT_MSG CUDA_HELPER_MATH_DIR)

if(CUDA_HELPER_MATH_DIR)
  set( CUDA_HELPER_MATH_FOUND TRUE)
endif(CUDA_HELPER_MATH_DIR)